spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    cofig:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888        